

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/vendor
    depends_on:
      - db
    networks:
      - absensi-net

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: absensi_db
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - absensi-net

  ngrok:
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "--domain=floral-procedure-masses.ngrok-free.dev"
      - "app:8000" # Ngrok mem-forward traffic ke container 'app' di port 8000
    ports:
      - "4040:4040" # Port untuk melihat web interface Ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - app
    networks:
      - absensi-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # Angka 8080 adalah port di Windows kamu
    environment:
      PMA_HOST: db # Harus sama dengan nama service database kamu
      PMA_USER: root
      PMA_PASSWORD: rootpassword # Sesuaikan dengan MYSQL_ROOT_PASSWORD kamu
    depends_on:
      - db
    networks:
      - absensi-net


networks:
  absensi-net:
    driver: bridge

volumes:
  db_data: